[package]
name = "vegemite"
version = "0.1.0"
edition = "2021"
description = "A Blazingly-fast http framework"
license = "MIT"

[dependencies]
http = "0.2.9"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
