[package]
name = "vegemite"
version = "0.1.1"
edition = "2021"
description = "A Blazingly-fast http framework"
license = "MIT"
repository = "https://github.com/Kay-Conte/vegemite-rs/"
categories = ["web-programming::http-server", "web-programming"]
rust-version = "1.65.0"

[features]
shuttle = ["dep:shuttle-service", "dep:async-trait"]

[dependencies]
http = "0.2.9"
shuttle-service = { version = "0.27.0", optional = true }
async-trait = { version = "0.1.73", optional = true }
