[package]
name = "vegemite"
version = "0.1.1"
edition = "2021"
description = "A Blazingly-fast http framework"
license = "MIT"
repository = "https://github.com/Kay-Conte/vegemite-rs/"
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
http = "0.2.9"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
