[package]
name = "turnip-http"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "0.2.9"
num_cpus = "1.16"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
